version: "3.9"
services:

  client-react-nginx:
    image: client-react-nginx
    build:
      context: ./client-react/
      dockerfile: ./client-react/Dockerfile.ng
    init: true
    networks:
      - frontend
    ports:
      - 80:8080
    restart: unless-stopped


  api-node:
    image: api-node
    # target only the dev stage because this compose is just for development purposes
    build:
      context: ./api-node/
      dockerfile: ./api-node/Dockerfile
      target: prod
    init: true
    volumes:
      - type: volume
        target: /usr/src/app/node_modules 
    depends_on:
      - db
    environment:
      - DATABASE_URL=postgres://postgres:foobarbaz@db:5432/postgres
    networks:
      - frontend
      - backend  
    ports:
      - 3000:3000
    restart: unless-stopped


  api-golang:
    image: api-golang
    build:
      context: ./api-golang/
      dockerfile: ./api-golang/Dockerfile
      target: prod
    init: true
    depends_on:
      - db
    environment:
      - DATABASE_URL=postgres://postgres:foobarbaz@db:5432/postgres
    networks:
      - frontend
      - backend
    ports:
      - 8080:8080
    restart: unless-stopped


  db:
    image: postgres:17.0-alpine3.19
    volumes:
      - pgdata:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=foobarbaz
    networks:
      - backend
    ports:
      - 5432:5432

volumes:
  pgdata:

networks:
  frontend:
  backend:

